@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

class AddCommand {
  - Person toAdd
  + AddCommand(Person)
  + CommandResult execute(Model)
}

class AddCommandParser {
  + AddCommand parse(String args)
}

class Person

AddCommand --> Person
AddCommandParser --> AddCommand
@enduml
