@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

class EditCommand {
  - Index index
  - EditPersonDescriptor editDescriptor
  + execute(Model): CommandResult
}

class EditPersonDescriptor {
  + get/set fields
  + isAnyFieldEdited(): boolean
}

class "<<interface>>\nModel" as Model

EditCommand --> EditPersonDescriptor
EditCommand --> Model
@enduml
